spring:
  application:
    name: client

  datasource:
    username: 'financeira'
    password: '123456'
    url: jdbc:postgresql://localhost:15432/db-client

  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'


    hibernate:
      ddl-auto: 'create-drop'
